[package]
name = "sl-verifiable-enc"
license-file = "../../LICENSE"
version = "0.1.0"
edition = "2021"
publish = ["silencelaboratories"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.9.3"
num-bigint-dig = "0.8.4"
group = "0.13.0"
ff = "0.13.0"
subtle = "2.5.0"
rand = { version = "0.8" }
rand_chacha = "0.3"
thiserror = "1"
sha2 = "0.10.8"

[dev-dependencies]
k256 = { version = "0.13.2", features = ["alloc", "serde"] }
curve25519-dalek = { version = "4.1.1", features = ["group"] }
